#ifndef STATIC_ASSERT_H_INCLUDED
#define STATIC_ASSERT_H_INCLUDED

#define STATIC_ASSERT(C,M) typedef int STATIC_ASSERTION_##M[(((!!(C))*1)-1)]
#define COMPILE_TIME_ASSERT3(C,L) STATIC_ASSERT(X,static_assertion_at_line_##L)
#define COMPILE_TIME_ASSERT2(C,L) COMPILE_TIME_ASSERT3(X,L)
#define COMPILE_TIME_ASSERT(C)    COMPILE_TIME_ASSERT2(X,__LINE__)

#endif
